### PR TITLE
Bugfix 1715 pb2nc seg fault with pbl 91

### LINKED ISSUE #1715: Fix pb2nc segfault when deriving PBL
## Describe the Problem ##

Mallory Row brought to our attention that when testing with her grid-to-obs use cases, she was getting segfaults with PB2NC.  She saw in the MET 9.1.2 release notes that there was a fix for this (https://github.com/dtcenter/MET/pull/1622), however she wasn't using the -index option like the release notes stated. 

Mallory put together a test case for this on the both the Dell and the Cray (WCOSS).  On the Dell, the case segfaults with 9.1, but not 9.1.2. On the Cray, it segfaults with both versions.
Dell: /gpfs/dell2/emc/verification/noscrub/emc.metplus/for_nco/met/met_test/case_6
Cray: /gpfs/hps3/emc/meso/noscrub/emc.metplus/for_nco/met/met_test/case_6
In README.txt is the command.

She turned up the verbosity to 5. The segfault came after this bit:
```
DEBUG 5: process_pbfile() PBL: excluded 0-th level record: T=-9999, U=-9999, V=-9999, Q=100000, Z=47 valid_time: 20210311_000000 ADPUPA 72363
DEBUG 5: process_pbfile() PBL: excluded 1-th level record: T=-9999, U=-9999, V=-9999, Q=92500, Z=722 valid_time: 20210311_000000 ADPUPA 72363
DEBUG 5: process_pbfile() Reverse levels
DEBUG 5: interpolate_by_pressure() interpolated count: 2
DEBUG 4: compute_pbl() interpolate Z (HGT)
DEBUG 5: interpolate_by_pressure() interpolated count: 4
DEBUG 4: compute_pbl() interpolate Q (SPFH)
DEBUG 5: process_pbfile() Reverse levels
Segmentation fault (core dumped)

```
She took "D_PBL" of the list to get variables from the prepbufr file, and she got no segfault, but with "D_PBL" in it segfaults.

### Expected Behavior ###
Segfaults are NEVER acceptable and always mean that there's some additional error checking we should add to the code.

### Environment ###
Describe your runtime environment:
*1. Machine: WCOSS Dell and Cray*
*2. OS: *
*3. Software version number(s): METv9.1 and METv9.1.2*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Get data from WCOSS once available*
*2. Run using the command in README.txt*
*3. See if the seg fault is reproducible on a local machine.  If not, text on WCOSS.*

### Relevant Deadlines ###
ASAP

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

The segmentation fault on computing PBL. It happened on cray machine (9.1.1 & 9.1.2). The problem happens when the TQ records and the UV records are overlapping to interpolate.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

```
/d1/personal/hsoh/git/bugfix/bugfix_1715_pb2nc_seg_fault_with_pbl_91/MET/met/bin/pb2nc /d1/personal/hsoh/data/MET-1715/nam.20210311.t00z.prepbufr.tm00 nam.20210311.t00z.prepbufr.tm00.pbl.nc /d1/personal/hsoh/data/MET-1715/PB2NCConfig_case_6 -v 6

log messages:
WARNING: combine_tqz_and_uv() Can not combine TQ and UV records because of no overlapping.
WARNING:              TQZ record count: 1, UV record count: 57  common_levels: 0
WARNING: Failed to compute PBL 20210311_000000 ADPUPA 72493
```

- [x] Do these changes include sufficient documentation and testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

## Summary of Updating ##
- Check if TQ records and UV are overlapping and display log messages if no overlapping
- Use nint instead of int for pressure values
- Additional check at interpolate_by_pressure and interpolate_pqtzuv

### CODE REVIEW

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 1]
```diff
@@ -2930,39 +2930,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
       if(mlog.verbosity_level() >= PBL_DEBUG_LEVEL) {
          log_tqz_and_uv(pqtzuv_map_tq, pqtzuv_map_uv, method_name);
       }
 
+      bool no_overlap = (tq_pres_max < uv_pres_min) || (tq_pres_min > uv_pres_max);
+      mlog << Debug(6) << method_name << "TQZ pressures: " << tq_pres_max
+           << " to " << tq_pres_min << "   UV pressures: " << uv_pres_max
+           << " to " << uv_pres_min << (no_overlap ? "  no overlap!" : "  overlapping") << "\n";
+      if( no_overlap ) {
+         mlog << Warning << method_name
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
         mlog << Warning << "\n" << method_name
```

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 2]
```diff
@@ -2930,39 +2930,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
+              << "Can not combine TQ and UV records because of no overlapping.\n";
+         mlog << Warning << "             TQZ record count: " << tq_count
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
         << "             TQZ record count: " << tq_count
```

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 3]
```diff
@@ -2930,39 +2930,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
          log_tqz_and_uv(pqtzuv_map_tq, pqtzuv_map_uv, method_name);
       }
 
+      bool no_overlap = (tq_pres_max < uv_pres_min) || (tq_pres_min > uv_pres_max);
+      mlog << Debug(6) << method_name << "TQZ pressures: " << tq_pres_max
+           << " to " << tq_pres_min << "   UV pressures: " << uv_pres_max
+           << " to " << uv_pres_min << (no_overlap ? "  no overlap!" : "  overlapping") << "\n";
+      if( no_overlap ) {
+         mlog << Warning << method_name
+              << "Can not combine TQ and UV records because of no overlapping.\n";
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
              << "Cannot combine TQ and UV records because of no pressure level overlap.\n"
```

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 4]
```diff
@@ -2930,39 +2930,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
+         mlog << Warning << "             TQZ record count: " << tq_count
+              << ", UV record count: " << uv_count
+              << "  common_levels: " << common_levels.n() << "\n";
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
              << "  common_levels: " << common_levels.n() << "\n\n";
```

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 5]
```diff
@@ -3229,11 +3262,13 @@ int interpolate_by_pressure(int length, float *pres_data, float *var_data) {
...
+   if ((nint(prev_pqtzuv[0]) == nint(cur_pqtzuv[0]))
+       || (nint(next_pqtzuv[0]) == nint(cur_pqtzuv[0]))
+       || (nint(prev_pqtzuv[0]) == nint(next_pqtzuv[0]))) {
       mlog << Error << method_name 
-              << "  Can't interpolate because of same pressure levels. prev: "
-              << prev_pqtzuv[0] << ", cur: " << cur_pqtzuv[0]
-              << ", next: " <<  prev_pqtzuv[0] << "\n";
+           << "  Can't interpolate because of same pressure levels. prev: "
+           << prev_pqtzuv[0] << ", cur: " << cur_pqtzuv[0]
+           << ", next: " <<  prev_pqtzuv[0] << "\n";
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc:3270]:
```suggestion
           << ", next: " <<  prev_pqtzuv[0] << "\n\n";
```

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 6]
```diff
@@ -3229,11 +3262,13 @@ int interpolate_by_pressure(int length, float *pres_data, float *var_data) {
 void interpolate_pqtzuv(float *prev_pqtzuv, float *cur_pqtzuv, float *next_pqtzuv) {
    static const char *method_name = "interpolate_pqtzuv() ";
 
-   if ((prev_pqtzuv[0] == cur_pqtzuv[0]) || (next_pqtzuv[0] == cur_pqtzuv[0])) {
+   if ((nint(prev_pqtzuv[0]) == nint(cur_pqtzuv[0]))
+       || (nint(next_pqtzuv[0]) == nint(cur_pqtzuv[0]))
+       || (nint(prev_pqtzuv[0]) == nint(next_pqtzuv[0]))) {
       mlog << Error << method_name
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
      mlog << Error << "\n" << method_name 
```

**Review by JohnHalleyGotway — APPROVED** [review]
Made suggestions for minor edits to the log warning/error log messages that are changed by this PR.

I did test these changes on kiowa in /d1/projects/MET/MET_pull_requests/met-9.1.3/feature_1715/MET-bugfix_1715_pb2nc_seg_fault_with_pbl_91_into_main_v9.1.
I ran unit_pb2nc.xml and diffed the output with recent main_v9.1 NB output. There are no differences, so low risk of unintended consequences.

@malloryprow already tested this patch on the WCOSS Cray machine and confirmed that it fixes the bug.

After accepting minor edits, please merge these changes into main_v9.1.
