### PR TITLE
Bugfix 2596 main v11.1 rpath compilation

### LINKED ISSUE #2596: Bugfix: Unknown ld Flag on Macos causes MET compilation to fail
## Describe the Problem ##
When using GCC@12 from the homebrew package manager MET fails to build due to an unknown ld flag _--disable-new-dtags_. Gives an error thatC compiler cannot create executables.

All the libraries appear to have built successfully. 

### Expected Behavior ###
MET tools should be able to determine what ld flags are needed based on OS.

### Environment ###
Describe your runtime environment:
*1. Machine: Virtual Mac Laptop*
*2. OS: Mac OS 13.1.4
*3. Software version number(s) MET 11.0.2

### To Reproduce ###
Describe the steps to reproduce the behavior:
`  echo "MET INSTALLING"
  brew install wget
  brew install git
  brew install gcc@12
  brew install libtool
  brew install automake
  brew install autoconf
  brew install make
  brew install m4
  brew install java
  brew install ksh
  brew install grads
  brew install ksh
  brew install tcsh
  brew install snap
  brew install python@3.11
  brew install cmake
  brew install xorgproto
  brew install xorgrgb
  brew install xauth
  brew install curl
  brew install flex
  brew install byacc
  brew install bison
  brew install gnu-sed

   pip3.11 install python-dateutil

    #Directory Listings
    mkdir $HOME/DTC
    export WRF_FOLDER=$HOME/DTC

    if [ "$WRFCHEM_PICK" = "1" ]; then
      mkdir $HOME/WRFCHEM
      export WRF_FOLDER=$HOME/WRFCHEM
    fi

    if [ "$WRFHYDRO_COUPLED_PICK" = "1" ]; then
      mkdir $HOME/WRFHYDRO_COUPLED
      export WRF_FOLDER=$HOME/WRFHYDRO_COUPLED
    fi

    if [ "$WRFHYDRO_STANDALONE_PICK" = "1" ]; then
      mkdir $HOME/WRFHYDRO_STANDALONE
      export WRF_FOLDER=$HOME/WRFHYDRO_STANDALONE
    fi

    if [ "$WRF_PICK" = "1" ]; then
      mkdir $HOME/WRF
      export WRF_FOLDER=$HOME/WRF
    fi

    if [ "$HWRF_PICK" = "1" ]; then
      mkdir $HOME/HWRF
      export WRF_FOLDER=$HOME/HWRF
    fi

    mkdir $WRF_FOLDER/MET-11.0.2
    mkdir $WRF_FOLDER/MET-11.0.2/Downloads
    mkdir $WRF_FOLDER/METplus-5.0.1
    mkdir $WRF_FOLDER/METplus-5.0.1/Downloads

      #Symlink to avoid clang conflicts with compilers
      #default gcc path /usr/bin/gcc
      #default homebrew path /usr/local/bin

      echo "Please enter password for linking GNU libraries"

      echo $PASSWD | sudo -S ln -sf /usr/local/bin/gcc-12 /usr/local/bin/gcc
      echo $PASSWD | sudo -S ln -sf /usr/local/bin/g++-12 /usr/local/bin/g++
      echo $PASSWD | sudo -S ln -sf /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
      echo $PASSWD | sudo -S ln -sf /usr/local/bin/python3.11 /usr/local/bin/python3

    cd $WRF_FOLDER/MET-11.0.2/Downloads

   wget -c -4 https://raw.githubusercontent.com/dtcenter/MET/main_v11.0/internal/scripts/installation/compile_MET_all.sh

    wget -c -4 https://dtcenter.ucar.edu/dfiles/code/METplus/MET/installation/tar_files.tgz

    wget -c -4 https://github.com/dtcenter/MET/archive/refs/tags/v11.0.2.tar.gz

    cp compile_MET_all.sh $WRF_FOLDER/MET-11.0.2
    tar -xvzf tar_files.tgz -C $WRF_FOLDER/MET-11.0.2
    cp v11.0.2.tar.gz $WRF_FOLDER/MET-11.0.2/tar_files
    cd $WRF_FOLDER/MET-11.0.2

    cd $WRF_FOLDER/MET-11.0.2

    export PYTHON_VERSION=$(python3 -V 2>1|awk '{print $2}')
    export PYTHON_VERSION_MAJOR_VERSION=$(echo $PYTHON_VERSION | awk -F. '{print $1}')
    export PYTHON_VERSION_MINOR_VERSION=$(echo $PYTHON_VERSION | awk -F. '{print $2}')
    export PYTHON_VERSION_COMBINED=$PYTHON_VERSION_MAJOR_VERSION.$PYTHON_VERSION_MINOR_VERSION

    export CC=/usr/local/bin/gcc
    export CXX=/usr/local/bin/g++
    export CFLAGS="-fPIC -fPIE -O3 -Wno-implicit-function-declaration"
    export FC=/usr/local/bin/gfortran
    export F77=/usr/local/bin/gfortran
    export F90=/usr/local/bin/gfortran
    export gcc_version=$(gcc -dumpfullversion)
    export TEST_BASE=$WRF_FOLDER/MET-11.0.2
    export COMPILER=gnu_$gcc_version
    export MET_SUBDIR=${TEST_BASE}
    export MET_TARBALL=v11.0.2.tar.gz
    export USE_MODULES=FALSE
    export MET_PYTHON=/usr/local/

    export MET_PYTHON_CC="-I$MET_PYTHON/opt/python@$PYTHON_VERSION_COMBINED/Frameworks/Python.framework/Versions/$PYTHON_VERSION_COMBINED/include/python$PYTHON_VERSION_COMBINED"
    export MET_PYTHON_LD="-L$MET_PYTHON/opt/python@$PYTHON_VERSION_COMBINED/Frameworks/Python.framework/Versions/$PYTHON_VERSION_COMBINED/lib/python$PYTHON_VERSION_COMBINED/config-$PYTHON_VERSION_COMBINED-darwin -lpython$PYTHON_VERSION_COMBINED -ldl -framework CoreFoundation"

    export SET_D64BIT=FALSE

    chmod 775 compile_MET_all.sh

    sed -i'' -e "831s/export/#export/g" compile_MET_all.sh
    time ./compile_MET_all.sh 2>&1 | tee compile_MET_all.log

[config.log](https://github.com/dtcenter/MET/files/11916752/config.log)
[configure.log](https://github.com/dtcenter/MET/files/11916753/configure.log)
[compile_MET_all.log](https://github.com/dtcenter/MET/files/11916754/compile_MET_all.log)

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
2792543

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tested compilation of METv11.1.0-rc1 and its dependent libraries on a MacOS (narya) using the gcc version 12.3.0 compiler and the 11.3.0 compiler.  I got a successful compilation using the 11.3.0 compiler, but not the 12.3.0 compiler (new issue to be created for this problem that seems unrelated to the script).
After reproducing the problem described in the issue, I was able to resolve the problem with these changes to the script and got a successful compilation and a successful run of "make test".  I also tested the changes in the script with METv11.1.0-rc1 and its dependent libraries the gcc version 12.1.0 compiler on cheyenne and got a successful compilation and a successful run of "make test".

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Review the files that changed and ensure that all tests pass.  You could compile on a Mac using gcc if desired, noting that MET won't compile, but that the errors seems unrelated to this script. (new issue to be created for this problem that seems unrelated to the script).
Note that @HathewayWill also tested the script, where the compilation of MET also failed, however the errors he received also seem unrelated to the script.  The errors he received were different from mine and were noted in the issue description for #2615.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[20230726]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

File: internal/scripts/installation/compile_MET_all.sh [hunk 1]
```diff
@@ -469,17 +486,33 @@ if [ $COMPILE_G2CLIB -eq 1 ]; then
   rm -rf ${LIB_DIR}/g2clib/g2clib*
   tar -xf ${TAR_DIR}/g2clib*.tar -C ${LIB_DIR}/g2clib
   cd ${LIB_DIR}/g2clib/g2clib*
-  # Sed commands use double-quotes to support variable expansion.
-  sed -i "s|INC=.*|INC=-I${LIB_DIR}/include -I${LIB_DIR}/include/jasper|g" makefile
+  
+  if [[ $machine == "Mac" ]]; then
```
Comment (georgemccabe) [inline internal/scripts/installation/compile_MET_all.sh]: There is a lot of duplication here. I think this could be simplified by creating a variable to store the the sed command to use based on the OS.

After the case statement (around line 356):

```
if [[ $machine == "Mac" ]]; then
    sed_inline="sed -i ''"
else
    sed_inline="sed -i''"
fi
```

then wherever you need to run a sed command, use the variable instead of "sed" e.g.

Before:
`sed -i '' "s|INC=.*|INC=-I${LIB_DIR}/include -I${LIB_DIR}/include/jasper|g" makefile`
After:
`$sed_inline "s|INC=.*|INC=-I${LIB_DIR}/include -I${LIB_DIR}/include/jasper|g" makefile`

File: internal/scripts/installation/compile_MET_all.sh [hunk 2]
```diff
@@ -563,13 +596,17 @@ if [ $COMPILE_NETCDF -eq 1 ]; then
...
   run_cmd "make ${MAKE_ARGS} install > netcdf-c.make_install.log 2>&1"
-
+  
   echo
   echo "Compiling NetCDF-CXX at `date`"
   tar -xzf ${TAR_DIR}/netcdf-cxx*.tar.gz -C ${LIB_DIR}/netcdf
   cd ${LIB_DIR}/netcdf/netcdf-cxx*
   echo "cd `pwd`"
-  run_cmd "./configure --prefix=${LIB_DIR} LDFLAGS=-L${LIB_DIR}/lib CPPFLAGS=-I${LIB_DIR}/include > netcdf-cxx.configure.log 2>&1"
+  if [[ $machine == "Mac" ]]; then
```
Comment (georgemccabe) [inline internal/scripts/installation/compile_MET_all.sh]: This could be simplified with a variable:

```
  configure_args=""
  if [[ $machine == "Mac" ]]; then 
    configure_args="LIBS=\"${LIBS} -lhdf5_hl -lhdf5 -lz\""
  fi
  run_cmd "./configure --prefix=${LIB_DIR} LDFLAGS=-L${LIB_DIR}/lib CPPFLAGS=-I${LIB_DIR}/include LIBS=\"${LIBS} ${configure_args}\"> netcdf-cxx.configure.log 2>&1"
```

File: internal/scripts/installation/compile_MET_all.sh [hunk 3]
```diff
@@ -276,6 +281,7 @@ echo "COMPILER = $COMPILER"
 echo "COMPILER_FAMILY = $COMPILER_FAMILY"
 echo "COMPILER_VERSION = $COMPILER_VERSION"
 COMPILER_MAJOR_VERSION=`echo $COMPILER_VERSION | cut -d'.' -f1`
+COMPILER_MINOR_VERSION=`echo $COMPILER_VERSION | cut -d'.' -f2`
```
Comment (georgemccabe) [inline internal/scripts/installation/compile_MET_all.sh:279]: Why was this added? I don't see it used anywhere in the script.

**Review by georgemccabe — CHANGES_REQUESTED** [review]
I made a few suggestions in-line to clean up the new logic to reduce duplicate code.

File: internal/scripts/installation/compile_MET_all.sh (hunk 3 above)
Comment (jprestop) [reply internal/scripts/installation/compile_MET_all.sh:279]: Thanks @georgemccabe.  I'll take a closer look at the other comments tomorrow, but I added the COMPILER_MAJOR_VERSION and COMPILER_MINOR_VERSION because it was originally thought that the problem lied with gcc 12.3.0.  It didn't, however, I could see potentially using these in the future so I left them in.

File: internal/scripts/installation/compile_MET_all.sh (hunk 1 above)
Comment (jprestop) [reply internal/scripts/installation/compile_MET_all.sh]: Thanks @georgemccabe for this simplification!  I'll change the code and retest to ensure the functionality still works.  I'll follow up.

File: internal/scripts/installation/compile_MET_all.sh (hunk 2 above)
Comment (jprestop) [reply internal/scripts/installation/compile_MET_all.sh]: Thanks @georgemccabe for this simplification!  I'll change the code and retest to ensure the functionality still works.  I'll follow up.

**Comment by jprestop** [comment]
Thanks @georgemccabe.  I made the suggested changes with a tweak and retested which results in the same outcome.  I'm going to remove @JohnHalleyGotway as a reviewer, since you have already been looking at this and will request a re-review from you.

File: internal/scripts/installation/compile_MET_all.sh [hunk 4]
```diff
@@ -541,15 +560,15 @@ fi
...
+  
   echo
   echo "Compiling HDF5 at `date`"
   mkdir -p ${LIB_DIR}/hdf5
   rm -rf ${LIB_DIR}/hdf5/hdf5*
   tar -xzf ${TAR_DIR}/hdf5*.tar.gz -C ${LIB_DIR}/hdf5
   cd ${LIB_DIR}/hdf5/hdf5*
   echo "cd `pwd`"
-  run_cmd "./configure --prefix=${LIB_DIR} --with-zlib=${LIB_Z} CFLAGS=-fPIC CXXFLAGS=-fPIC FFLAGS=-fPIC LDFLAGS=-L${LIB_DIR}/lib:${LIB_Z} CPPFLAGS=-I${LIB_DIR}/include > hdf5.configure.log 2>&1"
+  run_cmd "./configure --prefix=${LIB_DIR} --with-zlib=${LIB_Z} CFLAGS=-fPIC CXXFLAGS=-fPIC FFLAGS=-fPIC LDFLAGS=-L${LIB_DIR}/lib CPPFLAGS=-I${LIB_DIR}/include > hdf5.configure.log 2>&1"
```
Comment (georgemccabe) [inline internal/scripts/installation/compile_MET_all.sh]: Why was LIB_Z removed from the LDFLAGS here? Does it need to be set there if LIB_Z is set before running the script?

**Comment by jprestop** [comment]
@georgemccabe Thank you for you attention to detail.  That was removed during testing and never put back.  I'll add that back in and then will re-request a review.

**Review by georgemccabe — APPROVED** [review]
Looks good. Thanks for making the changes.

Line 595 doesn't need to be indented but that is not important.

Line 693: I'm not sure if exporting LDFLAGS to an empty string for MacOS is needed or not, but if it works it works.

I approve.

**Comment by jprestop** [comment]
@georgemccabe 

> Line 595 doesn't need to be indented but that is not important.

While not important, I want to be consistent, so I removed the indentation.  Thanks for noting that.
