### PR TITLE
feature_1552_gcc_10

### LINKED ISSUE #1552: Fix MET to compile using GCC version 10
## Describe the Task ##
As reported by a user via met-help (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97359) met-9.1 does not compile using the GCC version 10 compilers.  The issue lies with the compilation of the required BUFRLIB library:
`ufbtab.f:306:31:

  288 |          DO WHILE(IREADMG(-LUNIT,SUBSET,IDATE).GE.0)
      |                                        2
......
  306 | 10    IF(IREADMG(-LUNIT,SUBSET,JDATE).LT.0) GOTO 25
      |                               1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
ufbtab.f:534:37:

  288 |          DO WHILE(IREADMG(-LUNIT,SUBSET,IDATE).GE.0)
      |                                        2
......
  534 |       DO WHILE(IREADMG(-LUNIT,SUBSET,JDATE).GE.0)
      |                                     1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
`
I want to try to reproduce the problem using GCC version 10 and let the developers of BUFRLIB know of the issue.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- No sub-issues required. I expect this to only require a small number of changes.

### Relevant Deadlines ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required - no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by jprestop**
I added "-fallow-argument-mismatch" to the compilation of BUFRLIB and "-w -fallow-argument-mismatch" to the compilation of HDF4.2r3 to FFLAGS in the hdf/src/Makefile to get the successful compilation in the compile_MET_all.sh script. I also cleaned up bash comparison operators. I am checking in the install_met_env.cheyenne_gcc config file that I used for the compilation.

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Compiled MET successfully with HDF4, HDFEOS, Cairo, and Freetype using GNU 10.1.0 compilers on Cheyenne. 

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

A successful compilation exists on Cheyenne, with HDF4, HDFEOS, Cairo, and Freetype using GNU 10.1.0 compilers, the build and test logs can be reviewed at /glade/p/ral/jntp/MET/MET_cross_platform_testing/met-10.0.0-beta4/gcc/met-10.0.0-beta4 if desired.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

File: scripts/installation/compile_MET_all.sh [hunk 1]
```diff
@@ -128,18 +128,18 @@ COMPILER_VERSION=`echo $COMPILER | cut -d'_' -f2`
 
 echo "USE_MODULES = ${USE_MODULES}"
 
-if [ ${USE_MODULES} == "TRUE" ]; then 
+if [ ${USE_MODULES} = "TRUE" ]; then
```
Comment (JohnHalleyGotway) [inline scripts/installation/compile_MET_all.sh:131]: Julie, I'm concerned about all these instances of double '==' being changed to single '='. Won't that change it from a comparison operator to an assignment operator? This same difference exists in several places in this file.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
In compile_MET_all.sh I do not think all of the double '==' equals should have been changed to single '='. Please take a look.

File: scripts/installation/compile_MET_all.sh (hunk 1 above)
Comment (jprestop) [reply scripts/installation/compile_MET_all.sh:131]: Thank you for looking at this.  I thought the same thing too, but received a "[: ==: unary operator expected" message when running this code, which led me to this https://stackoverflow.com/questions/13617843/unary-operator-expected-error-in-bash-if-condition, where I noticed that only one "=" was being used for comparison, which led me to this
https://linuxize.com/post/how-to-compare-strings-in-bash/ which says:
```
Comparison operators are operators that compare values and return true or false. When comparing strings in Bash you can use the following operators:
string1 = string2 and string1 == string2 - The equality operator returns true if the operands are equal.
Use the = operator with the test [ command.
Use the == operator with the [[ command for pattern matching.
```
and gives some examples. I am no bash expert, so I don't really know.  Just following the guidance on these webpages and wanting to do it correctly.  Thoughts and/or suggestions?

Comment (JohnHalleyGotway) [reply scripts/installation/compile_MET_all.sh:131]: Julie, thanks for clarifying. I see other instances where we use [[ "a" == "b" ]] syntax. To avoid confusion do you want to switch those comparisons to [ "a" = "b" ] as well? Or is that inviting problems?

Comment (jprestop) [reply scripts/installation/compile_MET_all.sh:131]: In the examples from that webpage it says to:
```
Use the = operator with the test [ command.
Use the == operator with the [[ command for pattern matching.
```
So it looks like I should use one "=" for comparisons, when we use one bracket and two "==" for comparson when we use two brackets.  I'm not sure when to use one vs. two brackets either.  It looks like we should use one for a "test" and two for "pattern matching".  Maybe I should go back and check all for tests vs. pattern matching?  Thoughts?

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

File: scripts/installation/compile_MET_all.sh (hunk 1 above)
Comment (JohnHalleyGotway) [reply scripts/installation/compile_MET_all.sh:131]: I just approved the changes, as long as they actually work ;) Don't want to send us down an unnecessary rabbit hole hole here.

Comment (jprestop) [reply scripts/installation/compile_MET_all.sh:131]: Sounds good, John.  Thanks.  I'll be testing this when I start working on having MET compile with PGI v9 and for beta5, and can make additional updates as necessary in a future pull request.  I won't put this up on the website just yet and will likely wait until the official release.
