### PR TITLE
Bugfix #3164 develop slice range

### LINKED ISSUE #3164: Bugfix: Correct NetCDF dimension range checking to use inclusive inequalities
## Describe the Problem ##
This issue arose via the dtcenter/METplus#2970 discussion when reading monthly data from a NetCDF file with a time dimension of 12.

Grid-Stat was configured to extract climatology data for all 12 months from that file like this:
```
climo_mean = {

   file_name = ["era5_mnth.mrg1_avg.1440x0721.Y1985-2014.T00z.nc4"];
   field     = [ { name = "u"; level = "(0:11,@500,*,*)"; } ];
```
Where `0:11` indicates which 0-based time indices within that range should be used. `0:11` means that all of them should be used. However, runtime log messages indicate that data is read for time indices 0 through 10, but not 11:
```
DEBUG 7: MetNcCFDataFile::data_plane_array(VarInfo &, DataPlaneArray &) -> time: 19850115_000000 from index 0
DEBUG 7: MetNcCFDataFile::data_plane_array(VarInfo &, DataPlaneArray &) -> time: 19850214_000000 from index 1
...
DEBUG 7: MetNcCFDataFile::data_plane_array(VarInfo &, DataPlaneArray &) -> time: 19851111_000000 from index 10
```

### Expected Behavior ###
When specifying a range of dimension indices or values to be used, I would expect MET to use inclusive inequalities (e.g. including the endpoints of 0 and 11 in this example) rather the exclusive ones. For comparison, here's the [line of code](https://github.com/dtcenter/MET/blob/1e324fee337dbf9ee6abab80aac6ab2ad5257c1e/src/libcode/vx_data2d_grib/data2d_grib_utils.cc#L489) where ranges are checked for GRIB records:
```
if ( ( vinfo.level().type() != LevelType_Accum     ) &&
     ( vinfo.level().type() != LevelType_RecNumber ) &&
     ( grib_lower < lower || grib_upper > upper ) )  {

   mlog << Debug(4)
        << "For GRIB record number " << g.rec_num
        << ", the requested level values (" << lower << " and " << upper
        << ") do not fall within the current range of level values "
        << "(" << grib_lower << " and " << grib_upper << ").\n";

   return false;
}
```
It *discards* any records < min or > max which is the same as *keeping* any records >= min and <= max.

Please review the logic in the MET NetCDF library code to consistently include both endpoints in the ranges.

Please fix this in both the `main_v12.1` and `develop` branches.

### To Reproduce ###
Run this script: `seneca:/d1/projects/METplus/discussions/2970/run_gs.sh`

### Relevant Deadlines ###
Recommend fixing for the upcoming MET-12.1.0 official release.

### Funding Source ###
Please use NCAR base, but if time surpasses 8 h, please contact @michelleharrold 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next bugfix version
- [x] Select **METplus-X.Y Support** project for support of the current coordinated release
- [x] Select **MET-X.Y Development** project for development toward the next coordinated release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y Development** project for development toward the next coordinated release
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Expected Differences ##

The main change is including upper bound for the range of indexes (0:10 ==> include 11 levels instead of 10 levels) to make the same behavior with GRIB.

- Support two @ notations at time and vlevel
- Other bug fixes with @notation and range of offsets
- Allow vertical level range for the plot_data_plane. It will give a log message which level was selected

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- Modified plot_data_plane unitest (offset 0 to time string).
- Modified `plot_data_plane_NCCF_latlon_by_value` with two @ notations: `name = "edr"; level = "(@20130730_00,@20000,*,*)";'`

./grid_stat wrfprs_ruc13_03.tm00_G212 wrfprs_ruc13_03.tm00_G212 GridStatConfig.test -outdir out -v 10

note: GridStatConfig.test was from /d1/projects/METplus/discussions/2970/GridStatConfig.
Other data and configuration files were from /d1/projects/METplus/discussions/2970

```
netcdf era5_mnth.mrg1_avg.1440x0721.Y1985-2014.T00z {
dimensions:
        time = UNLIMITED ; // (12 currently)
        lev = 37 ;
        lat = 721 ;
        lon = 1440 ;
```
   `field     = [ { name = "u"; level = "(0:10,0,*,*)"; } ];`  ==>  to test inclusive range
```
DEBUG 7: VarInfoNcCF::set_magic() ->  start: 0, end: 10
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 0
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 1
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 2
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 3
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 4
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 5
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 6
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 7
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 8
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 9
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 10
DEBUG 7: MetNcCFDataFile::collect_time_offsets(VarInfo &) -> Found 11 times between 19850115_000000 and 19851211_000000
```

   `field     = [ { name = "u"; level = "(0:21,0,*,*)"; } ];`  ==>  upper bound of time is beyond time dimension
```
DEBUG 7: VarInfoNcCF::set_magic() ->  start: 0, end: 21
DEBUG 7: MetNcCFDataFile::collect_time_offsets(VarInfo &) -> Ignored index above dimension size (12)
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 0
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 1
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 2
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 3
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 4
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 5
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 6
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 7
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 8
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 9
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 10
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 11
DEBUG 7: MetNcCFDataFile::collect_time_offsets(VarInfo &) -> Found 12 times between 19850115_000000 and 19851211_000000
```
   `field     = [ { name = "u"; level = "(0,0-50,*,*)"; } ];`
```
DEBUG 4: VarInfoFactory::new_var_info() -> created new VarInfo object of type "FileType_NcCF".
DEBUG 7: MetNcCFDataFile::collect_z_offsets(VarInfo &) -> Ignored index above dimension size (37)
...
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  added index 37
DEBUG 7: MetNcCFDataFile::collect_z_offsets(VarInfo &) -> Found 38 vlevels between 1 and 1000
D
```
   `field     = [ { name = "u"; level = "(0:5,@500,*,*)"; } ];`
```
DEBUG 7: MetNcCFDataFile::convert_z_to_offset() -> Found "lev" dimension value of "500" at dimension index 21.
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 0
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 1
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 2
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 3
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 4
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  added index 5
DEBUG 7: MetNcCFDataFile::collect_time_offsets(VarInfo &) -> Found 6 times between 19850115_000000 and 19851211_000000
```
   `field     = [ { name = "u"; level = "(@19850714:19850813,@500,*,*)"; } ];`
```
DEBUG 7: MetNcCFDataFile::convert_z_to_offset() -> Found "lev" dimension value of "500" at dimension index 21.
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  found the first time 19850714_000000 level lower: [19850714_000000]
DEBUG 9: MetNcCFDataFile::collect_time_offsets(VarInfo &) ->  found the time 19850813_000000
DEBUG 7: MetNcCFDataFile::collect_time_offsets(VarInfo &) -> Found 2 times between 19850115_000000 and 19851211_000000
D
```
   `field     = [ { name = "u"; level = "(@19850115,@400-800,*,*)"; } ];`
   `field     = [ { name = "u"; level = "(@19850115,@400-@800,*,*)"; } ];`
```
DEBUG 7: MetNcCFDataFile::convert_time_to_offset() -> Found 19850115_000000 at index 0 from time value
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the first z 400 lower: [400]
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 450
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 500
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 550
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 600
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 650
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 700
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 750
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 775
DEBUG 9: MetNcCFDataFile::collect_z_offsets(VarInfo &) ->  found the z 800
DEBUG 7: MetNcCFDataFile::collect_z_offsets(VarInfo &) -> Found 10 vlevels between 1 and 1000
```

Range of vertical levels for plot_data_plane:
```
bin/plot_data_plane       /d1/projects/MET/MET_test_data/unit_test/model_data/nccf/gtg/lc/gtg_obs_forecast.20130404.i12.f06.nc       /d1/personal/hsoh/MET/test_output/bugfix_3164_slice_range/plot_data_plane/gtg_obs_forecast.20130404.i12.f06.NCCF_lc_25.ps       'name = "edr"; level = "(@20130404_18,0-1,*,*)";'       -title "NCCF Lambert Conformal 1000ft"       -v 9

DEBUG 1: Start plot_data_plane V12.1.0 by hsoh(9895) at 2025-06-13 18:44:52Z with command: bin/plot_data_plane /d1/projects/MET/MET_test_data/unit_test/model_data/nccf/gtg/lc/gtg_obs_forecast.20130404.i12.f06.nc /d1/personal/hsoh/MET/test_output/bugfix_3164_slice_range/plot_data_plane/gtg_obs_forecast.20130404.i12.f06.NCCF_lc_25.ps name = "edr"; level = "(@20130404_18,0-1,*,*)"; -title NCCF Lambert Conformal 1000ft -v 9

==>
DEBUG 1: MetNcCFDataFile::find_z_offset() -> the lowerest level [0] was selected between 0 and 1
```

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the MET test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Will this PR result in changes to existing METplus Use Cases? **[Yes or No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **METplus-X.Y Support** project for bugfix releases or **MET-X.Y Development** project for the next coordinated release
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

File: src/libcode/vx_data2d_nc_cf/data2d_nc_cf.cc [hunk 1]
```diff
@@ -688,10 +834,245 @@ long MetNcCFDataFile::convert_value_to_offset(double z_value, string z_dim_name)
...
+      // Store the name of the first data variable
+      data_var = find_first_data_var();
+      vinfo.set_req_name(data_var->name.c_str());
+   }
+   else data_var = _file->find_var_name(vinfo.req_name().c_str());
+
+   return data_var;
+}
+
+///////////////////////////////////////////////////////////////////////////////////////////////////////////////
```
Comment (JohnHalleyGotway) [inline src/libcode/vx_data2d_nc_cf/data2d_nc_cf.cc]:
```suggestion
/////////////////////////////////////////////////////////////////////////
```

File: src/libcode/vx_data2d_nc_cf/data2d_nc_cf.cc [hunk 2]
```diff
@@ -688,10 +834,245 @@ long MetNcCFDataFile::convert_value_to_offset(double z_value, string z_dim_name)
...
+string MetNcCFDataFile::get_z_dim_name(const NcVarInfo *data_var) const {
+   string z_dim_name;
+   if (0 <= data_var->z_slot) {
+      NcDim z_dim = get_nc_dim(data_var->var, data_var->z_slot);
+      if (IS_VALID_NC(z_dim)) z_dim_name = GET_NC_NAME(z_dim);
+   }
+   return z_dim_name;
+}
+
+///////////////////////////////////////////////////////////////////////////////////////////////////////////////
```
Comment (JohnHalleyGotway) [inline src/libcode/vx_data2d_nc_cf/data2d_nc_cf.cc]:
```suggestion
/////////////////////////////////////////////////////////////////////////
```

File: src/libcode/vx_data2d_nc_cf/data2d_nc_cf.cc [hunk 3]
```diff
@@ -688,10 +834,245 @@ long MetNcCFDataFile::convert_value_to_offset(double z_value, string z_dim_name)
...
+
+   if( ( vinfo.valid() != 0         && _file->ValidTime[0] != vinfo.valid() ) ||
+       ( vinfo.init()  != 0         && _file->InitTime     != vinfo.init()  ) ||
+       ( !is_bad_data(vinfo.lead()) && _file->lead_time()  != vinfo.lead()  ) )
+      return -1;
+
+   return 0;
+}
+
+//////////////////////////////////
```
Comment (JohnHalleyGotway) [inline src/libcode/vx_data2d_nc_cf/data2d_nc_cf.cc]:
```suggestion
/////////////////////////////////////////////////////////////////////////
```

**Review by JohnHalleyGotway — COMMENTED** [review]
Note that I did propose a few minor edits for consistent formatting.
I tested in seneca `/d1/projects/MET/MET_pull_requests/met-12.2.0/rc1/MET-bugfix_3164_slice_range`. With `plot_data_plane` and I found slightly inconsistent behavior for handling bad inputs:
```
cd /d1/projects/MET/MET_pull_requests/met-12.2.0/rc1/MET-bugfix_3164_slice_range

# Bad time request results in a library ERROR
bin/plot_data_plane  $MET_TEST_INPUT/model_data/nccf/gtg/latlon/gtg_obs_forecast.20130730.i00.f00.nc plot.ps 'name="edr"; level="(@20130731,@380,*,*)";'
ERROR  : MetNcCFDataFile::find_time_offset() -> the requested time 20130731_000000 for "edr" variable does not exist (20130730_000000 and 20130730_000000).

# Bad level request results in a library WARNING
bin/plot_data_plane  $MET_TEST_INPUT/model_data/nccf/gtg/latlon/gtg_obs_forecast.20130730.i00.f00.nc plot.ps 'name="edr"; level="(@20130730,@380,*,*)";'
WARNING: MetNcCFDataFile::find_z_offset() -> the requested vlevel 380 for "edr" variable does not exist (20000 and 45000).
```
Should these both be warnings? Or both be errors?

I also note:
1. No differences are flagged by GHA.
2. SonarQube code smells are reduced by this PR by 32 (from 15,617 to 15,585).
3. Existing unit tests are modified to demonstrate that replacing the time index with `YYYYMMDD_HH` notation OR `@YYYYMMDD_HH` notation produces the same result.
4. Manually ran a few tests to confirm that it behaves as expected with good inputs.

**Review by JohnHalleyGotway — COMMENTED** [review]
Duplicate

**Comment by hsoh-u** [comment]
> Note that I did propose a few minor edits for consistent formatting. I tested in seneca `/d1/projects/MET/MET_pull_requests/met-12.2.0/rc1/MET-bugfix_3164_slice_range`. With `plot_data_plane` and I found slightly inconsistent behavior for handling bad inputs:
> 
> ```
> cd /d1/projects/MET/MET_pull_requests/met-12.2.0/rc1/MET-bugfix_3164_slice_range
> 
> # Bad time request results in a library ERROR
> bin/plot_data_plane  $MET_TEST_INPUT/model_data/nccf/gtg/latlon/gtg_obs_forecast.20130730.i00.f00.nc plot.ps 'name="edr"; level="(@20130731,@380,*,*)";'
> ERROR  : MetNcCFDataFile::find_time_offset() -> the requested time 20130731_000000 for "edr" variable does not exist (20130730_000000 and 20130730_000000).
> 
> # Bad level request results in a library WARNING
> bin/plot_data_plane  $MET_TEST_INPUT/model_data/nccf/gtg/latlon/gtg_obs_forecast.20130730.i00.f00.nc plot.ps 'name="edr"; level="(@20130730,@380,*,*)";'
> WARNING: MetNcCFDataFile::find_z_offset() -> the requested vlevel 380 for "edr" variable does not exist (20000 and 45000).
> ```
> 
> Should these both be warnings? Or both be errors?
> 
> I also note:
> 
> 1. No differences are flagged by GHA.
> 2. SonarQube code smells are reduced by this PR by 32 (from 15,617 to 15,585).
> 3. Existing unit tests are modified to demonstrate that replacing the time index with `YYYYMMDD_HH` notation OR `@YYYYMMDD_HH` notation produces the same result.
> 4. Manually ran a few tests to confirm that it behaves as expected with good inputs.

It's an error and will be stopped.

> Note that I did propose a few minor edits for consistent formatting. I tested in seneca `/d1/projects/MET/MET_pull_requests/met-12.2.0/rc1/MET-bugfix_3164_slice_range`. With `plot_data_plane` and I found slightly inconsistent behavior for handling bad inputs:
> 
> ```
> cd /d1/projects/MET/MET_pull_requests/met-12.2.0/rc1/MET-bugfix_3164_slice_range
> 
> # Bad time request results in a library ERROR
> bin/plot_data_plane  $MET_TEST_INPUT/model_data/nccf/gtg/latlon/gtg_obs_forecast.20130730.i00.f00.nc plot.ps 'name="edr"; level="(@20130731,@380,*,*)";'
> ERROR  : MetNcCFDataFile::find_time_offset() -> the requested time 20130731_000000 for "edr" variable does not exist (20130730_000000 and 20130730_000000).
> 
> # Bad level request results in a library WARNING
> bin/plot_data_plane  $MET_TEST_INPUT/model_data/nccf/gtg/latlon/gtg_obs_forecast.20130730.i00.f00.nc plot.ps 'name="edr"; level="(@20130730,@380,*,*)";'
> WARNING: MetNcCFDataFile::find_z_offset() -> the requested vlevel 380 for "edr" variable does not exist (20000 and 45000).
> ```
> 
> Should these both be warnings? Or both be errors?
> 
> I also note:
> 
> 1. No differences are flagged by GHA.
> 2. SonarQube code smells are reduced by this PR by 32 (from 15,617 to 15,585).
> 3. Existing unit tests are modified to demonstrate that replacing the time index with `YYYYMMDD_HH` notation OR `@YYYYMMDD_HH` notation produces the same result.
> 4. Manually ran a few tests to confirm that it behaves as expected with good inputs.

It should be an error and be stopped in order to avoid to read a NetCDF variable with bad offset. It's fixed

**Review by JohnHalleyGotway — APPROVED** [review]
I approve of these changes.

Thanks for updating the logic to consistently error our for bad vertical level or timestring values. I confirmed that both cases error out as expected:
```
ERROR  : MetNcCFDataFile::find_time_offset() -> the requested time 20130731_000000 for "edr" variable does not exist (20130730_000000 and 20130730_000000).
...
ERROR  : MetNcCFDataFile::find_z_offset() -> the requested vlevel 380 for "edr" variable does not exist (20000 and 45000).
```
