### PR TITLE
Bugfix 1715 pb2nc seg fault with pbl

### LINKED ISSUE #1715: Fix pb2nc segfault when deriving PBL
## Describe the Problem ##

Mallory Row brought to our attention that when testing with her grid-to-obs use cases, she was getting segfaults with PB2NC.  She saw in the MET 9.1.2 release notes that there was a fix for this (https://github.com/dtcenter/MET/pull/1622), however she wasn't using the -index option like the release notes stated. 

Mallory put together a test case for this on the both the Dell and the Cray (WCOSS).  On the Dell, the case segfaults with 9.1, but not 9.1.2. On the Cray, it segfaults with both versions.
Dell: /gpfs/dell2/emc/verification/noscrub/emc.metplus/for_nco/met/met_test/case_6
Cray: /gpfs/hps3/emc/meso/noscrub/emc.metplus/for_nco/met/met_test/case_6
In README.txt is the command.

She turned up the verbosity to 5. The segfault came after this bit:
```
DEBUG 5: process_pbfile() PBL: excluded 0-th level record: T=-9999, U=-9999, V=-9999, Q=100000, Z=47 valid_time: 20210311_000000 ADPUPA 72363
DEBUG 5: process_pbfile() PBL: excluded 1-th level record: T=-9999, U=-9999, V=-9999, Q=92500, Z=722 valid_time: 20210311_000000 ADPUPA 72363
DEBUG 5: process_pbfile() Reverse levels
DEBUG 5: interpolate_by_pressure() interpolated count: 2
DEBUG 4: compute_pbl() interpolate Z (HGT)
DEBUG 5: interpolate_by_pressure() interpolated count: 4
DEBUG 4: compute_pbl() interpolate Q (SPFH)
DEBUG 5: process_pbfile() Reverse levels
Segmentation fault (core dumped)

```
She took "D_PBL" of the list to get variables from the prepbufr file, and she got no segfault, but with "D_PBL" in it segfaults.

### Expected Behavior ###
Segfaults are NEVER acceptable and always mean that there's some additional error checking we should add to the code.

### Environment ###
Describe your runtime environment:
*1. Machine: WCOSS Dell and Cray*
*2. OS: *
*3. Software version number(s): METv9.1 and METv9.1.2*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Get data from WCOSS once available*
*2. Run using the command in README.txt*
*3. See if the seg fault is reproducible on a local machine.  If not, text on WCOSS.*

### Relevant Deadlines ###
ASAP

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by hsoh-u**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

The segmentation fault on computing PBL. It happened on cray machine (9.1.1 & 9.1.2). The problem happens when the TQ records and the UV records are overlapping to interpolate.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

```
/d1/personal/hsoh/git/bugfix/bugfix_1715_pb2nc_seg_fault_with_pbl/MET/met/bin/pb2nc /d1/personal/hsoh/data/MET-1715/nam.20210311.t00z.prepbufr.tm00 nam.20210311.t00z.prepbufr.tm00.pbl.nc /d1/personal/hsoh/data/MET-1715/PB2NCConfig_case_6_10 -v 6

log messages:
WARNING: combine_tqz_and_uv() Can not combine TQ and UV records because of no overlapping.
WARNING:              TQZ record count: 1, UV record count: 57  common_levels: 0
WARNING: Failed to compute PBL 20210311_000000 ADPUPA 72493
```
- [x] Do these changes include sufficient documentation and testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Added an unit test and one more output: pb2nc/nam.20210311.t00z.prepbufr.tm00.pbl.nc

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

## Summary of Updating ##
- Check if TQ records and UV are overlapping and display log messages if no overlapping
- Use nint instead of int for pressure values
- Additional check at interpolate_by_pressure and interpolate_pqtzuv
- Added one unit test which compute PBL and CAPE

### CODE REVIEW

File: test/config/PB2NCConfig_pbl [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+level_category = [0, 1, 4, 5, 6];
+
+///////////////////////////////////////////////////////////////////////////////
+
+//
+// BUFR variable names to retain or derive.
+// Use obs_bufr_map to rename variables in the output.
+// If empty, process all available variables.
+//
+obs_bufr_var = ["TOB", "UOB", "VOB", "TOCC", "D_RH", "TDO", "PMO", "HOVI", "CEILING", "MXGS", "D_CAPE", "D_PBL"];
```
Comment (JohnHalleyGotway) [inline test/config/PB2NCConfig_pbl]:
```suggestion
obs_bufr_var = ["D_PBL"];
```
Since we're testing the PBL derivation, is it sufficient to request that only PBL be derived?

File: test/config/PB2NCConfig_pbl [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+//obs_bufr_var = ["TOB", "UOB", "VOB", "TOCC", "D_RH", "TDO", "PMO", "HOVI", "CEILING", "MXGS", "D_CAPE"];
```
Comment (JohnHalleyGotway) [inline test/config/PB2NCConfig_pbl]:
```suggestion
```
Rather than commenting out a previous setting, I'd prefer to remove it entirely to keep the config file as clean as possible.

File: test/config/PB2NCConfig_pbl [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+   beg =  -1000;
+   end = 100000;
+}
+
+////////////////////////////////////////////////////////////////////////////////
+
+//
+// Observation types
+//
+pb_report_type  = [ 120, 220, 221, 122, 222, 223, 224, 131, 133, 233, 153, 156, 157, 180, 280, 181, 182, 281, 282, 183, 284, 187, 287 ];
```
Comment (JohnHalleyGotway) [inline test/config/PB2NCConfig_pbl]:
```suggestion
pb_report_type  = [];
```
Do we actually NEED to explicitly list all these report types? Or is it sufficient to have an empty list so that all are processed?

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 4]
```diff
@@ -2920,39 +2920,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
+            common_levels.add(nint(pres_v));
          }
       }
 
       if(mlog.verbosity_level() >= PBL_DEBUG_LEVEL) {
          log_tqz_and_uv(pqtzuv_map_tq, pqtzuv_map_uv, method_name);
       }
 
+      bool no_overlap = (tq_pres_max < uv_pres_min) || (tq_pres_min > uv_pres_max);
+      mlog << Debug(6) << method_name << "TQZ pressures: " << tq_pres_max
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc:2952]:
```suggestion
      mlog << Debug(6) << "\n" << method_name << "TQZ pressures: " << tq_pres_max
```
Like Error messages, the Warning messages in MET start with a new line and end with a new line to make them stand out in the log file.

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 5]
```diff
@@ -2920,39 +2920,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
+           << " to " << tq_pres_min << "   UV pressures: " << uv_pres_max
+           << " to " << uv_pres_min << (no_overlap ? "  no overlap!" : "  overlapping") << "\n";
+      if( no_overlap ) {
+         mlog << Warning << method_name
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
         mlog << Warning << "\n" << method_name
```
Like Error messages, the Warning messages in MET start with a new line and end with a new line to make them stand out in the log file.

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 6]
```diff
@@ -2920,39 +2920,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
+              << "Can not combine TQ and UV records because of no overlapping.\n";
+         mlog << Warning << "             TQZ record count: " << tq_count
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
         << "             TQZ record count: " << tq_count
```
No need to start a new warning message. Just continue the old one.

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 7]
```diff
@@ -2920,39 +2920,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
          log_tqz_and_uv(pqtzuv_map_tq, pqtzuv_map_uv, method_name);
       }
 
+      bool no_overlap = (tq_pres_max < uv_pres_min) || (tq_pres_min > uv_pres_max);
+      mlog << Debug(6) << method_name << "TQZ pressures: " << tq_pres_max
+           << " to " << tq_pres_min << "   UV pressures: " << uv_pres_max
+           << " to " << uv_pres_min << (no_overlap ? "  no overlap!" : "  overlapping") << "\n";
+      if( no_overlap ) {
+         mlog << Warning << method_name
+              << "Can not combine TQ and UV records because of no overlapping.\n";
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
              << "Can not combine TQ and UV records because of no overlapping.\n"
```

File: met/src/tools/other/pb2nc/pb2nc.cc [hunk 8]
```diff
@@ -2920,39 +2920,65 @@ int combine_tqz_and_uv(map<float, float*> pqtzuv_map_tq,
...
+         mlog << Warning << "             TQZ record count: " << tq_count
+              << ", UV record count: " << uv_count
+              << "  common_levels: " << common_levels.n() << "\n";
```
Comment (JohnHalleyGotway) [inline met/src/tools/other/pb2nc/pb2nc.cc]:
```suggestion
              << "  common_levels: " << common_levels.n() << "\n\n";
```
Terminate Error and Warning messages with 2 new lines.

**Review by JohnHalleyGotway — CHANGES_REQUESTED** [review]
Thanks for adding the new unit tests. I made some suggestions to make the new unit test more concise and also use consistent formatting for warning messages in pb2nc.
Throughout MET the Warning and Error messages begin with 1 newline and end with 2. That has the effect of surrounding each Warning and Error message with a blank line before/after. The goal is to make them stand out in the logfile and is a hold-over from Randy Bullock's coding style. I'm torn on whether on not I like that convention because it's so hard to remember! But since it's in place, let's just follow it.

Please check the rest of pb2nc.cc to make sure warnings/errors start with 1 newline and end with 2.

**Comment by hsoh-u** [comment]
Added D_CAPE to obs_bufr_var:

obs_bufr_var = ["D_CAPE", "D_PBL"];

**Review by JohnHalleyGotway — APPROVED** [review]
Looks great Howard. Thanks for making the updates. I approve.

FYI, I did test this on kiowa in /d1/projects/MET/MET_pull_requests/met-10.0.0_beta5/feature_1715. I ran unit_pb2nc.xml and confirm that the only changes are the addition of the new output file from pb2nc.
