### PR TITLE
Bugfix #2402 develop sonarqube

### LINKED ISSUE #2402: Bugfix: Address MET-11.0.0 SonarQube Blocker Bugs
## Describe the Problem ##
The SonarQube scan of the MET-11.0.0 released code flagged several issues with bugs with a blocker status. This results in an error status of the scan. Recommend addressing these issues ASAP and resolving them in a MET-11.0.1 bugfix release. Fix any issues that can be addressed directly. Document justification for any issues that cannot be fixed directly.

See the nightly SonarQube scans: http://mandan.rap.ucar.edu:9000
Also see the Excel and Word summaries:
[2023-01-11-MET Nightly build-issues-report.xlsx](https://github.com/dtcenter/MET/files/10406395/2023-01-11-MET.Nightly.build-issues-report.xlsx)
[2023-01-11-MET Nightly build-analysis-report.docx](https://github.com/dtcenter/MET/files/10406397/2023-01-11-MET.Nightly.build-analysis-report.docx)

### Expected Behavior ###
*Provide a clear and concise description of what you expected to happen here.*

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
After porting over the changes, I just confirmed that the code still compiles. But the GHA testing workflow will also test that.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Make sure that the GHA testing workflow doesn't flag any diffs.
Briefly review the code changes.
I don't have a good way to prove that the findings are reduced by these change (as I did for MET#2447). Once these changers are merged into develop, we should see the existing [MET NB blocker bugs](http://mandan.rap.ucar.edu:9000/dashboard?id=MET_develop_NB) reduce from 22 down to 10.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
None needed.

- [x] Do these changes include sufficient testing updates? **[Yes]**
None needed.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Mon 2/27/23]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

File: src/tools/other/mode_graphics/cgraph_font.cc [hunk 1]
```diff
@@ -115,7 +115,7 @@ face = 0;
 if ( !get_env(cg_font_env, gs_font_dir) )  {
 
    mlog << Error
-        << "\n\n  CgFont::init_from_scratch() -> "
+        << "\nCgFont::init_from_scratch() -> "
```
Comment (hsoh-u) [inline src/tools/other/mode_graphics/cgraph_font.cc:118]: Minor style: two line breaks for error message

File: src/tools/other/mode_graphics/cgraph_font.cc [hunk 2]
```diff
@@ -258,7 +258,8 @@ clear();
 
 if ( (n < 0) || (n >= total_predef_fonts) )  {
 
-   mlog << Error << "\n\n  CgFont::set_by_number(int) -> range check error\n\n";
+   mlog << Error << "\nCgFont::set_by_number(int) -> "
```
Comment (hsoh-u) [inline src/tools/other/mode_graphics/cgraph_font.cc:261]: Minor style: two line breaks for error message

File: src/tools/other/mode_graphics/cgraph_font.cc [hunk 3]
```diff
@@ -274,7 +275,8 @@ full_afm_name << gs_font_dir << '/' << gs_font_dir << '/' << short_afm_name;
 
 if ( !file_exists(full_afm_name.c_str()) )  {
 
-   mlog << Error << "\n\n  CgFont::set_by_number(int) -> can't find afm file \"" << full_afm_name << "\"\n\n";
+   mlog << Error << "\nCgFont::set_by_number(int) -> "
```
Comment (hsoh-u) [inline src/tools/other/mode_graphics/cgraph_font.cc:278]: Minor style: two line breaks for error message

**Review by hsoh-u — APPROVED** [review]
I approve of these changes. 
I ran the unittest manually and compared the outputs with reference run at seneca. No differences for the output. I also ran cppchecker which runs on Windows OS and no finding by cppchecker.

**Comment by hsoh-u** [comment]
Unit test runtime difference (at seneca)
Note: first time is from Nightly build and the second time is my unit test run.
I did not check if it uses new code or not.
Case of longer execution time
```
TEST: pcp_combine_sum_GRIB1                    - pass -  19.163 sec
TEST: pcp_combine_sum_GRIB1                    - pass - 206.842 sec
```
Cases of faster execution time:
```
TEST: ascii2nc_WWSIS_clear_pvwatts_one_min   - pass -  60.852 sec
TEST: ascii2nc_WWSIS_clear_pvwatts_one_min   - pass -  14.048 sec

TEST: ascii2nc_WWSIS_pvwatts_one_min         - pass -  62.444 sec
TEST: ascii2nc_WWSIS_pvwatts_one_min         - pass -  14.252 sec
```
